package gapi

import (
	_ "embed"
	"encoding/json"
	"net/http"
	"strings"
)

// swaggerSpec is the generated OpenAPI JSON, embedded into the binary at build time.
// It is generated by running: make proto
// Source: doc/swagger/go_bank.swagger.json
//
//go:embed go_bank.swagger.json
var swaggerSpec []byte

// swaggerMeta holds the minimal fields we parse from the embedded spec
// to auto-populate the UI title, version badge, and description.
type swaggerMeta struct {
	Info struct {
		Title       string `json:"title"`
		Version     string `json:"version"`
		Description string `json:"description"`
	} `json:"info"`
}

// parseSwaggerMeta extracts title/version/description from the embedded spec.
// Falls back to sensible defaults if parsing fails.
func parseSwaggerMeta() swaggerMeta {
	var meta swaggerMeta
	meta.Info.Title = "GoBank API"
	meta.Info.Version = "1.0.0"
	_ = json.Unmarshal(swaggerSpec, &meta)
	return meta
}

// SwaggerHandler serves:
//
//	GET /swagger/          → custom branded Swagger UI
//	GET /swagger/doc.json  → raw embedded OpenAPI spec (for tooling / generated clients)
//
// The spec is auto-embedded at build time — no runtime file path dependency.
// Title, version, and description are read directly from the spec itself.
func SwaggerHandler(w http.ResponseWriter, r *http.Request) {
	switch {

	// --- Raw spec (useful for Postman import, openapi-generator, etc.) ---
	case r.URL.Path == "/swagger/doc.json":
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-cache")
		w.Write(swaggerSpec)

	// --- Swagger UI ---
	default:
		meta := parseSwaggerMeta()
		html := buildSwaggerUI(meta)
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache")
		w.Write([]byte(html))
	}
}

// buildSwaggerUI returns the full HTML for the custom branded Swagger UI.
// Project name, version, and description are injected from the parsed spec metadata.
func buildSwaggerUI(meta swaggerMeta) string {
	// Trim description to a short tagline for the hero section
	tagline := meta.Info.Description
	if idx := strings.Index(tagline, "\n"); idx > 0 {
		tagline = tagline[:idx]
	}
	if len(tagline) > 120 {
		tagline = tagline[:120] + "…"
	}

	return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>` + meta.Info.Title + ` · API Docs</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🏦</text></svg>" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />

  <style>
    :root {
      --bg:          #0a0c10;
      --surface:     #111418;
      --surface2:    #181c22;
      --border:      #1f252e;
      --accent:      #00d4aa;
      --accent-dim:  #00d4aa22;
      --accent2:     #f59e0b;
      --text:        #e2e8f0;
      --text-muted:  #64748b;
      --text-faint:  #334155;
      --danger:      #ef4444;
      --success:     #22c55e;
      --warning:     #f59e0b;
      --info:        #3b82f6;
      --font-display: 'Syne', sans-serif;
      --font-mono:    'JetBrains Mono', monospace;
      --radius:       10px;
      --radius-sm:    6px;
      --glow:         0 0 40px #00d4aa18;
    }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; }

    body {
      background: var(--bg);
      color: var(--text);
      font-family: var(--font-mono);
      min-height: 100vh;
      overflow-x: hidden;
    }

    body::before {
      content: '';
      position: fixed;
      inset: 0;
      background-image:
        linear-gradient(var(--border) 1px, transparent 1px),
        linear-gradient(90deg, var(--border) 1px, transparent 1px);
      background-size: 40px 40px;
      opacity: 0.4;
      pointer-events: none;
      z-index: 0;
    }

    #gobank-header {
      position: relative;
      z-index: 10;
      padding: 52px 48px 40px;
      border-bottom: 1px solid var(--border);
      background: linear-gradient(180deg, #0d1117 0%, transparent 100%);
    }

    .header-inner {
      max-width: 1100px;
      margin: 0 auto;
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 32px;
      flex-wrap: wrap;
    }

    .header-left { flex: 1; min-width: 280px; }

    .logo-row {
      display: flex;
      align-items: center;
      gap: 14px;
      margin-bottom: 12px;
    }

    .logo-icon {
      width: 44px;
      height: 44px;
      background: var(--accent-dim);
      border: 1px solid var(--accent);
      border-radius: var(--radius-sm);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 22px;
      box-shadow: var(--glow);
      animation: pulse-border 3s ease-in-out infinite;
    }

    @keyframes pulse-border {
      0%, 100% { box-shadow: 0 0 20px #00d4aa18; }
      50%       { box-shadow: 0 0 40px #00d4aa40; }
    }

    .api-title {
      font-family: var(--font-display);
      font-size: 28px;
      font-weight: 800;
      color: var(--text);
      letter-spacing: -0.5px;
      line-height: 1;
    }

    .api-title span { color: var(--accent); }

    .api-tagline {
      font-size: 13px;
      color: var(--text-muted);
      line-height: 1.6;
      max-width: 520px;
      margin-top: 2px;
    }

    .header-right {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 12px;
    }

    .badge-row {
      display: flex;
      align-items: center;
      gap: 8px;
      flex-wrap: wrap;
      justify-content: flex-end;
    }

    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 12px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 500;
      letter-spacing: 0.4px;
      border: 1px solid;
      font-family: var(--font-mono);
    }

    .badge-version  { background: var(--accent-dim); border-color: var(--accent);  color: var(--accent);  }
    .badge-grpc     { background: #3b82f608;          border-color: #3b82f6;        color: #3b82f6;        }
    .badge-paseto   { background: #f59e0b08;          border-color: var(--accent2); color: var(--accent2); }

    .spec-link {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 7px 14px;
      background: var(--surface2);
      border: 1px solid var(--border);
      border-radius: var(--radius-sm);
      color: var(--text-muted);
      text-decoration: none;
      font-size: 12px;
      transition: all 0.15s ease;
    }

    .spec-link:hover {
      border-color: var(--accent);
      color: var(--accent);
      background: var(--accent-dim);
    }

    .stats-bar {
      max-width: 1100px;
      margin: 0 auto;
      padding: 16px 0 0;
      display: flex;
      gap: 32px;
      flex-wrap: wrap;
    }

    .stat {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 12px;
      color: var(--text-muted);
    }

    .stat-dot {
      width: 6px;
      height: 6px;
      border-radius: 50%;
      background: var(--accent);
      box-shadow: 0 0 6px var(--accent);
    }

    #swagger-ui-wrap {
      position: relative;
      z-index: 5;
      max-width: 1100px;
      margin: 0 auto;
      padding: 32px 48px 80px;
    }

    /* ── Swagger UI overrides ── */
    .swagger-ui .topbar,
    .swagger-ui .info  { display: none !important; }

    .swagger-ui { color: var(--text) !important; background: transparent !important; }

    .swagger-ui .scheme-container {
      background: var(--surface) !important;
      border: 1px solid var(--border) !important;
      border-radius: var(--radius) !important;
      padding: 12px 20px !important;
      box-shadow: none !important;
      margin-bottom: 24px !important;
    }

    .swagger-ui .opblock-tag {
      font-family: var(--font-display) !important;
      font-size: 13px !important;
      font-weight: 700 !important;
      color: var(--text) !important;
      border-bottom: 1px solid var(--border) !important;
      padding: 14px 0 !important;
      letter-spacing: 1.5px !important;
      text-transform: uppercase !important;
    }

    .swagger-ui .opblock {
      background: var(--surface) !important;
      border: 1px solid var(--border) !important;
      border-radius: var(--radius) !important;
      margin-bottom: 8px !important;
      box-shadow: none !important;
      transition: border-color 0.15s ease !important;
    }

    .swagger-ui .opblock:hover { border-color: #2a3140 !important; }

    .swagger-ui .opblock.opblock-post   { border-left: 3px solid var(--success) !important; }
    .swagger-ui .opblock.opblock-get    { border-left: 3px solid var(--info) !important; }
    .swagger-ui .opblock.opblock-put    { border-left: 3px solid var(--warning) !important; }
    .swagger-ui .opblock.opblock-delete { border-left: 3px solid var(--danger) !important; }
    .swagger-ui .opblock.opblock-patch  { border-left: 3px solid #8b5cf6 !important; }

    .swagger-ui .opblock-summary { background: transparent !important; padding: 12px 16px !important; }

    .swagger-ui .opblock-summary-method {
      font-family: var(--font-mono) !important;
      font-size: 11px !important;
      font-weight: 500 !important;
      letter-spacing: 0.5px !important;
      border-radius: var(--radius-sm) !important;
      min-width: 70px !important;
    }

    .swagger-ui .opblock-summary-path        { font-family: var(--font-mono) !important; font-size: 13px !important; color: var(--text) !important; }
    .swagger-ui .opblock-summary-description { font-size: 12px !important; color: var(--text-muted) !important; }

    .swagger-ui .opblock-body,
    .swagger-ui .opblock-section,
    .swagger-ui .tab-header { background: var(--surface2) !important; }

    .swagger-ui .opblock-description-wrapper p,
    .swagger-ui .markdown p,
    .swagger-ui .renderedMarkdown p { color: var(--text-muted) !important; font-size: 13px !important; }

    .swagger-ui table thead tr th,
    .swagger-ui table thead tr td {
      background: var(--bg) !important;
      color: var(--text-muted) !important;
      font-family: var(--font-mono) !important;
      font-size: 11px !important;
      letter-spacing: 0.8px !important;
      border-bottom: 1px solid var(--border) !important;
      padding: 10px 12px !important;
    }

    .swagger-ui table tbody tr td {
      background: transparent !important;
      border-bottom: 1px solid var(--border) !important;
      color: var(--text) !important;
      font-size: 13px !important;
      padding: 10px 12px !important;
    }

    .swagger-ui input[type=text],
    .swagger-ui input[type=password],
    .swagger-ui input[type=email],
    .swagger-ui textarea,
    .swagger-ui select {
      background: var(--bg) !important;
      border: 1px solid var(--border) !important;
      border-radius: var(--radius-sm) !important;
      color: var(--text) !important;
      font-family: var(--font-mono) !important;
      font-size: 13px !important;
    }

    .swagger-ui input:focus,
    .swagger-ui textarea:focus {
      border-color: var(--accent) !important;
      outline: none !important;
      box-shadow: 0 0 0 2px var(--accent-dim) !important;
    }

    .swagger-ui .btn { font-family: var(--font-mono) !important; font-size: 12px !important; border-radius: var(--radius-sm) !important; transition: all 0.15s ease !important; }
    .swagger-ui .btn.execute { background: var(--accent) !important; border-color: var(--accent) !important; color: #000 !important; font-weight: 600 !important; }
    .swagger-ui .btn.execute:hover { background: #00f0c0 !important; box-shadow: var(--glow) !important; }
    .swagger-ui .btn.authorize { background: transparent !important; border-color: var(--accent) !important; color: var(--accent) !important; }
    .swagger-ui .btn.authorize:hover { background: var(--accent-dim) !important; }

    .swagger-ui .highlight-code,
    .swagger-ui .microlight { background: var(--bg) !important; border-radius: var(--radius-sm) !important; font-family: var(--font-mono) !important; font-size: 12px !important; }

    .swagger-ui .response-col_status { font-family: var(--font-mono) !important; font-weight: 600 !important; font-size: 13px !important; }

    .swagger-ui .dialog-ux .modal-ux { background: var(--surface) !important; border: 1px solid var(--border) !important; border-radius: var(--radius) !important; box-shadow: 0 25px 60px #00000080 !important; }
    .swagger-ui .dialog-ux .modal-ux-header { background: var(--surface2) !important; border-bottom: 1px solid var(--border) !important; }
    .swagger-ui .dialog-ux .modal-ux-header h3 { color: var(--text) !important; font-family: var(--font-display) !important; }

    .swagger-ui section.models { border: 1px solid var(--border) !important; border-radius: var(--radius) !important; background: var(--surface) !important; }
    .swagger-ui section.models h4 { font-family: var(--font-display) !important; color: var(--text) !important; }
    .swagger-ui .model-box { background: var(--bg) !important; }
    .swagger-ui .model { color: var(--text) !important; }
    .swagger-ui .prop-type { color: var(--accent) !important; }
    .swagger-ui .prop-format { color: var(--text-muted) !important; }

    ::-webkit-scrollbar { width: 6px; height: 6px; }
    ::-webkit-scrollbar-track { background: var(--bg); }
    ::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
    ::-webkit-scrollbar-thumb:hover { background: var(--text-faint); }

    @media (max-width: 768px) {
      #gobank-header { padding: 32px 20px 24px; }
      #swagger-ui-wrap { padding: 24px 20px 60px; }
      .header-right { align-items: flex-start; }
      .badge-row { justify-content: flex-start; }
    }
  </style>
</head>
<body>

  <header id="gobank-header">
    <div class="header-inner">
      <div class="header-left">
        <div class="logo-row">
          <div class="logo-icon">🏦</div>
          <h1 class="api-title">Go<span>Bank</span></h1>
        </div>
        <p class="api-tagline">` + tagline + `</p>
        <div class="stats-bar">
          <div class="stat"><span class="stat-dot"></span>gRPC + REST Gateway</div>
          <div class="stat"><span class="stat-dot" style="background:#3b82f6;box-shadow:0 0 6px #3b82f6"></span>PASETO Auth</div>
          <div class="stat"><span class="stat-dot" style="background:#f59e0b;box-shadow:0 0 6px #f59e0b"></span>Atomic Transfers</div>
        </div>
      </div>

      <div class="header-right">
        <div class="badge-row">
          <span class="badge badge-version">v` + meta.Info.Version + `</span>
          <span class="badge badge-grpc">gRPC-Gateway</span>
          <span class="badge badge-paseto">PASETO</span>
        </div>
        <a class="spec-link" href="/swagger/doc.json" target="_blank">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          OpenAPI JSON
        </a>
      </div>
    </div>
  </header>

  <div id="swagger-ui-wrap">
    <div id="swagger-ui"></div>
  </div>

  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url: "/swagger/doc.json",
      dom_id: "#swagger-ui",
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset,
      ],
      plugins: [SwaggerUIBundle.plugins.DownloadUrl],
      layout: "BaseLayout",
      deepLinking: true,
      displayRequestDuration: true,
      defaultModelsExpandDepth: 2,
      defaultModelExpandDepth: 2,
      docExpansion: "list",
      filter: true,
      showExtensions: true,
      showCommonExtensions: true,
      tryItOutEnabled: true,
      persistAuthorization: true,
      syntaxHighlight: { activate: true, theme: "monokai" },
    });
  </script>
</body>
</html>`
}