// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rpc_entry.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityEntry struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            int64                   `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               int64                   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                  `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TransferId           *wrapperspb.Int64Value  `protobuf:"bytes,6,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	CounterpartAccountId *wrapperspb.Int64Value  `protobuf:"bytes,7,opt,name=counterpart_account_id,json=counterpartAccountId,proto3" json:"counterpart_account_id,omitempty"`
	CounterpartOwner     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=counterpart_owner,json=counterpartOwner,proto3" json:"counterpart_owner,omitempty"`
	CounterpartCurrency  *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=counterpart_currency,json=counterpartCurrency,proto3" json:"counterpart_currency,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActivityEntry) Reset() {
	*x = ActivityEntry{}
	mi := &file_rpc_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEntry) ProtoMessage() {}

func (x *ActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEntry.ProtoReflect.Descriptor instead.
func (*ActivityEntry) Descriptor() ([]byte, []int) {
	return file_rpc_entry_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityEntry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ActivityEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ActivityEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ActivityEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActivityEntry) GetTransferId() *wrapperspb.Int64Value {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *ActivityEntry) GetCounterpartAccountId() *wrapperspb.Int64Value {
	if x != nil {
		return x.CounterpartAccountId
	}
	return nil
}

func (x *ActivityEntry) GetCounterpartOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.CounterpartOwner
	}
	return nil
}

func (x *ActivityEntry) GetCounterpartCurrency() *wrapperspb.StringValue {
	if x != nil {
		return x.CounterpartCurrency
	}
	return nil
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int32                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_rpc_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_entry_proto_rawDescGZIP(), []int{1}
}

func (x *ListEntriesRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListEntriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ActivityEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_rpc_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_entry_proto_rawDescGZIP(), []int{2}
}

func (x *ListEntriesResponse) GetEntries() []*ActivityEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_rpc_entry_proto protoreflect.FileDescriptor

const file_rpc_entry_proto_rawDesc = "" +
	"\n" +
	"\x0frpc_entry.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa9\b\n" +
	"\rActivityEntry\x12.\n" +
	"\x02id\x18\x01 \x01(\x03B\x1e\x92A\x1b2\x19Unique activity entry ID.R\x02id\x12N\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03B/\x92A,2!The account that owns this entry.i\x00\x00\x00\x00\x00\x00\xf0?R\taccountId\x12n\n" +
	"\x06amount\x18\x03 \x01(\x03BV\x92AS2JAmount in the smallest currency unit. Negative = debit, positive = credit.J\x0550000R\x06amount\x12_\n" +
	"\bcurrency\x18\x04 \x01(\tBC\x92A@27ISO 4217 currency of the account this entry belongs to.J\x05\"USD\"R\bcurrency\x12i\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB.\x92A+2)UTC timestamp when the entry was created.R\tcreatedAt\x12\xa0\x01\n" +
	"\vtransfer_id\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueBb\x92A_2]Transfer ID when this entry was created by an internal transfer; null for manual adjustments.R\n" +
	"transferId\x12\xa0\x01\n" +
	"\x16counterpart_account_id\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueBM\x92AJ2HCounterpart account ID on the other side of the transfer when available.R\x14counterpartAccountId\x12\x89\x01\n" +
	"\x11counterpart_owner\x18\b \x01(\v2\x1c.google.protobuf.StringValueB>\x92A;29Owner username of the counterpart account when available.R\x10counterpartOwner\x12\x89\x01\n" +
	"\x14counterpart_currency\x18\t \x01(\v2\x1c.google.protobuf.StringValueB8\x92A523Currency of the counterpart account when available.R\x13counterpartCurrency\"\xb1\x01\n" +
	"\x12ListEntriesRequest\x12>\n" +
	"\apage_id\x18\x01 \x01(\x05B%\x92A\"2\x141-based page number.J\x011i\x00\x00\x00\x00\x00\x00\xf0?R\x06pageId\x12[\n" +
	"\tpage_size\x18\x02 \x01(\x05B>\x92A;2#Number of entries per page. Max 50.J\x0220Y\x00\x00\x00\x00\x00\x00I@i\x00\x00\x00\x00\x00\x00\xf0?R\bpageSize\"B\n" +
	"\x13ListEntriesResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.pb.ActivityEntryR\aentriesB(Z&github.com/a7medalyapany/GoBank.git/pbb\x06proto3"

var (
	file_rpc_entry_proto_rawDescOnce sync.Once
	file_rpc_entry_proto_rawDescData []byte
)

func file_rpc_entry_proto_rawDescGZIP() []byte {
	file_rpc_entry_proto_rawDescOnce.Do(func() {
		file_rpc_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_entry_proto_rawDesc), len(file_rpc_entry_proto_rawDesc)))
	})
	return file_rpc_entry_proto_rawDescData
}

var file_rpc_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_entry_proto_goTypes = []any{
	(*ActivityEntry)(nil),          // 0: pb.ActivityEntry
	(*ListEntriesRequest)(nil),     // 1: pb.ListEntriesRequest
	(*ListEntriesResponse)(nil),    // 2: pb.ListEntriesResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),  // 4: google.protobuf.Int64Value
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_rpc_entry_proto_depIdxs = []int32{
	3, // 0: pb.ActivityEntry.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: pb.ActivityEntry.transfer_id:type_name -> google.protobuf.Int64Value
	4, // 2: pb.ActivityEntry.counterpart_account_id:type_name -> google.protobuf.Int64Value
	5, // 3: pb.ActivityEntry.counterpart_owner:type_name -> google.protobuf.StringValue
	5, // 4: pb.ActivityEntry.counterpart_currency:type_name -> google.protobuf.StringValue
	0, // 5: pb.ListEntriesResponse.entries:type_name -> pb.ActivityEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_entry_proto_init() }
func file_rpc_entry_proto_init() {
	if File_rpc_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_entry_proto_rawDesc), len(file_rpc_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_entry_proto_goTypes,
		DependencyIndexes: file_rpc_entry_proto_depIdxs,
		MessageInfos:      file_rpc_entry_proto_msgTypes,
	}.Build()
	File_rpc_entry_proto = out.File
	file_rpc_entry_proto_goTypes = nil
	file_rpc_entry_proto_depIdxs = nil
}
