// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rpc_account.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_rpc_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AccountLookUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLookUp) Reset() {
	*x = AccountLookUp{}
	mi := &file_rpc_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLookUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLookUp) ProtoMessage() {}

func (x *AccountLookUp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLookUp.ProtoReflect.Descriptor instead.
func (*AccountLookUp) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountLookUp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountLookUp) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AccountLookUp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 4217 currency code. Supported: USD, EUR, EGP.
	// Each user may only hold one account per currency.
	Currency      string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_rpc_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_rpc_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_rpc_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_rpc_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int32                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_rpc_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccountsRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_rpc_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_rpc_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccountRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_rpc_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_rpc_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_rpc_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LookUpAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookUpAccountRequest) Reset() {
	*x = LookUpAccountRequest{}
	mi := &file_rpc_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookUpAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookUpAccountRequest) ProtoMessage() {}

func (x *LookUpAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookUpAccountRequest.ProtoReflect.Descriptor instead.
func (*LookUpAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{12}
}

func (x *LookUpAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LookUpAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountLookUp         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookUpAccountResponse) Reset() {
	*x = LookUpAccountResponse{}
	mi := &file_rpc_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookUpAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookUpAccountResponse) ProtoMessage() {}

func (x *LookUpAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookUpAccountResponse.ProtoReflect.Descriptor instead.
func (*LookUpAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_proto_rawDescGZIP(), []int{13}
}

func (x *LookUpAccountResponse) GetAccount() *AccountLookUp {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_rpc_account_proto protoreflect.FileDescriptor

const file_rpc_account_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_account.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x86\x03\n" +
	"\aAccount\x12'\n" +
	"\x02id\x18\x01 \x01(\x03B\x17\x92A\x142\x12Unique account ID.R\x02id\x129\n" +
	"\x05owner\x18\x02 \x01(\tB#\x92A 2\x1eUsername of the account owner.R\x05owner\x12i\n" +
	"\abalance\x18\x03 \x01(\x01BO\x92AL2ACurrent balance in major currency unit (e.g. dollars, not cents).J\a1050.75R\abalance\x12?\n" +
	"\bcurrency\x18\x04 \x01(\tB#\x92A 2\x17ISO 4217 currency code.J\x05\"USD\"R\bcurrency\x12k\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB0\x92A-2+UTC timestamp when the account was created.R\tcreatedAt\"\xb4\x01\n" +
	"\rAccountLookUp\x12'\n" +
	"\x02id\x18\x01 \x01(\x03B\x17\x92A\x142\x12Unique account ID.R\x02id\x129\n" +
	"\x05owner\x18\x02 \x01(\tB#\x92A 2\x1eUsername of the account owner.R\x05owner\x12?\n" +
	"\bcurrency\x18\x04 \x01(\tB#\x92A 2\x17ISO 4217 currency code.J\x05\"USD\"R\bcurrency\"\x9c\x01\n" +
	"\x14CreateAccountRequest\x12\x83\x01\n" +
	"\bcurrency\x18\x01 \x01(\tBg\x92Ad2[ISO 4217 currency code. Supported values: USD, EUR, EGP. One account per currency per user.J\x05\"USD\"R\bcurrency\">\n" +
	"\x15CreateAccountResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\"x\n" +
	"\x11GetAccountRequest\x12c\n" +
	"\x02id\x18\x01 \x01(\x03BS\x92AP2EID of the account to retrieve. Must belong to the authenticated user.i\x00\x00\x00\x00\x00\x00\xf0?R\x02id\";\n" +
	"\x12GetAccountResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\"\xb4\x01\n" +
	"\x13ListAccountsRequest\x12>\n" +
	"\apage_id\x18\x01 \x01(\x05B%\x92A\"2\x141-based page number.J\x011i\x00\x00\x00\x00\x00\x00\xf0?R\x06pageId\x12]\n" +
	"\tpage_size\x18\x02 \x01(\x05B@\x92A=2%Number of accounts per page. Max 100.J\x0210Y\x00\x00\x00\x00\x00\x00Y@i\x00\x00\x00\x00\x00\x00\xf0?R\bpageSize\"?\n" +
	"\x14ListAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.pb.AccountR\baccounts\"\xe2\x01\n" +
	"\x14UpdateAccountRequest\x12a\n" +
	"\x02id\x18\x01 \x01(\x03BQ\x92AN2CID of the account to update. Must belong to the authenticated user.i\x00\x00\x00\x00\x00\x00\xf0?R\x02id\x12g\n" +
	"\abalance\x18\x02 \x01(\x01BM\x92AJ2@New balance in major currency unit (e.g. dollars). Must be >= 0.J\x06500.00R\abalance\">\n" +
	"\x15UpdateAccountResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\"y\n" +
	"\x14DeleteAccountRequest\x12a\n" +
	"\x02id\x18\x01 \x01(\x03BQ\x92AN2CID of the account to delete. Must belong to the authenticated user.i\x00\x00\x00\x00\x00\x00\xf0?R\x02id\"V\n" +
	"\x15DeleteAccountResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\tB%\x92A\"2\x15Confirmation message.J\t\"deleted\"R\x06status\"R\n" +
	"\x14LookUpAccountRequest\x12:\n" +
	"\x02id\x18\x01 \x01(\x03B*\x92A'2\x1cID of the account to lookup.i\x00\x00\x00\x00\x00\x00\xf0?R\x02id\"D\n" +
	"\x15LookUpAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.pb.AccountLookUpR\aaccountB(Z&github.com/a7medalyapany/GoBank.git/pbb\x06proto3"

var (
	file_rpc_account_proto_rawDescOnce sync.Once
	file_rpc_account_proto_rawDescData []byte
)

func file_rpc_account_proto_rawDescGZIP() []byte {
	file_rpc_account_proto_rawDescOnce.Do(func() {
		file_rpc_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_account_proto_rawDesc), len(file_rpc_account_proto_rawDesc)))
	})
	return file_rpc_account_proto_rawDescData
}

var file_rpc_account_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_account_proto_goTypes = []any{
	(*Account)(nil),               // 0: pb.Account
	(*AccountLookUp)(nil),         // 1: pb.AccountLookUp
	(*CreateAccountRequest)(nil),  // 2: pb.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 3: pb.CreateAccountResponse
	(*GetAccountRequest)(nil),     // 4: pb.GetAccountRequest
	(*GetAccountResponse)(nil),    // 5: pb.GetAccountResponse
	(*ListAccountsRequest)(nil),   // 6: pb.ListAccountsRequest
	(*ListAccountsResponse)(nil),  // 7: pb.ListAccountsResponse
	(*UpdateAccountRequest)(nil),  // 8: pb.UpdateAccountRequest
	(*UpdateAccountResponse)(nil), // 9: pb.UpdateAccountResponse
	(*DeleteAccountRequest)(nil),  // 10: pb.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 11: pb.DeleteAccountResponse
	(*LookUpAccountRequest)(nil),  // 12: pb.LookUpAccountRequest
	(*LookUpAccountResponse)(nil), // 13: pb.LookUpAccountResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_rpc_account_proto_depIdxs = []int32{
	14, // 0: pb.Account.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: pb.CreateAccountResponse.account:type_name -> pb.Account
	0,  // 2: pb.GetAccountResponse.account:type_name -> pb.Account
	0,  // 3: pb.ListAccountsResponse.accounts:type_name -> pb.Account
	0,  // 4: pb.UpdateAccountResponse.account:type_name -> pb.Account
	1,  // 5: pb.LookUpAccountResponse.account:type_name -> pb.AccountLookUp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_account_proto_init() }
func file_rpc_account_proto_init() {
	if File_rpc_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_account_proto_rawDesc), len(file_rpc_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_account_proto_goTypes,
		DependencyIndexes: file_rpc_account_proto_depIdxs,
		MessageInfos:      file_rpc_account_proto_msgTypes,
	}.Build()
	File_rpc_account_proto = out.File
	file_rpc_account_proto_goTypes = nil
	file_rpc_account_proto_depIdxs = nil
}
