// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rpc_transfer.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferEntry) Reset() {
	*x = TransferEntry{}
	mi := &file_rpc_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEntry) ProtoMessage() {}

func (x *TransferEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEntry.ProtoReflect.Descriptor instead.
func (*TransferEntry) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferEntry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TransferEntry) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TransferRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccountId int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRecord) Reset() {
	*x = TransferRecord{}
	mi := &file_rpc_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRecord) ProtoMessage() {}

func (x *TransferRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRecord.ProtoReflect.Descriptor instead.
func (*TransferRecord) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferRecord) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferRecord) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_rpc_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Transfer      *TransferRecord                         `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	FromEntry     *TransferEntry                          `protobuf:"bytes,2,opt,name=from_entry,json=fromEntry,proto3" json:"from_entry,omitempty"`
	ToEntry       *TransferEntry                          `protobuf:"bytes,3,opt,name=to_entry,json=toEntry,proto3" json:"to_entry,omitempty"`
	FromAccount   *CreateTransferResponse_AccountSnapshot `protobuf:"bytes,4,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     *CreateTransferResponse_AccountSnapshot `protobuf:"bytes,5,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_rpc_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransferResponse) GetTransfer() *TransferRecord {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *CreateTransferResponse) GetFromEntry() *TransferEntry {
	if x != nil {
		return x.FromEntry
	}
	return nil
}

func (x *CreateTransferResponse) GetToEntry() *TransferEntry {
	if x != nil {
		return x.ToEntry
	}
	return nil
}

func (x *CreateTransferResponse) GetFromAccount() *CreateTransferResponse_AccountSnapshot {
	if x != nil {
		return x.FromAccount
	}
	return nil
}

func (x *CreateTransferResponse) GetToAccount() *CreateTransferResponse_AccountSnapshot {
	if x != nil {
		return x.ToAccount
	}
	return nil
}

// Updated account snapshots after the atomic transaction
// Use these instead of re-fetching to avoid stale reads.
type CreateTransferResponse_AccountSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse_AccountSnapshot) Reset() {
	*x = CreateTransferResponse_AccountSnapshot{}
	mi := &file_rpc_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse_AccountSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse_AccountSnapshot) ProtoMessage() {}

func (x *CreateTransferResponse_AccountSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse_AccountSnapshot.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse_AccountSnapshot) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateTransferResponse_AccountSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTransferResponse_AccountSnapshot) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateTransferResponse_AccountSnapshot) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateTransferResponse_AccountSnapshot) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_rpc_transfer_proto protoreflect.FileDescriptor

const file_rpc_transfer_proto_rawDesc = "" +
	"\n" +
	"\x12rpc_transfer.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd2\x01\n" +
	"\rTransferEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12W\n" +
	"\x06amount\x18\x03 \x01(\x01B?\x92A<2:Amount in major currency unit. Negative for debit entries.R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x81\x02\n" +
	"\x0eTransferRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12X\n" +
	"\x06amount\x18\x04 \x01(\x01B@\x92A=2;Transferred amount in major currency unit. Always positive.R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcf\x03\n" +
	"\x15CreateTransferRequest\x12x\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03BP\x92AM2BID of the account to debit. Must belong to the authenticated user.i\x00\x00\x00\x00\x00\x00\xf0?R\rfromAccountId\x12f\n" +
	"\rto_account_id\x18\x02 \x01(\x03BB\x92A?24ID of the account to credit. Can belong to any user.i\x00\x00\x00\x00\x00\x00\xf0?R\vtoAccountId\x12j\n" +
	"\x06amount\x18\x03 \x01(\x01BR\x92AO2FAmount to transfer in major currency unit (e.g. dollars). Must be > 0.J\x0510.50R\x06amount\x12h\n" +
	"\bcurrency\x18\x04 \x01(\tBL\x92AI2@Currency of the transfer. Both accounts must hold this currency.J\x05\"USD\"R\bcurrency\"\xb1\x03\n" +
	"\x16CreateTransferResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.pb.TransferRecordR\btransfer\x120\n" +
	"\n" +
	"from_entry\x18\x02 \x01(\v2\x11.pb.TransferEntryR\tfromEntry\x12,\n" +
	"\bto_entry\x18\x03 \x01(\v2\x11.pb.TransferEntryR\atoEntry\x12M\n" +
	"\ffrom_account\x18\x04 \x01(\v2*.pb.CreateTransferResponse.AccountSnapshotR\vfromAccount\x12I\n" +
	"\n" +
	"to_account\x18\x05 \x01(\v2*.pb.CreateTransferResponse.AccountSnapshotR\ttoAccount\x1am\n" +
	"\x0fAccountSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrencyB(Z&github.com/a7medalyapany/GoBank.git/pbb\x06proto3"

var (
	file_rpc_transfer_proto_rawDescOnce sync.Once
	file_rpc_transfer_proto_rawDescData []byte
)

func file_rpc_transfer_proto_rawDescGZIP() []byte {
	file_rpc_transfer_proto_rawDescOnce.Do(func() {
		file_rpc_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_transfer_proto_rawDesc), len(file_rpc_transfer_proto_rawDesc)))
	})
	return file_rpc_transfer_proto_rawDescData
}

var file_rpc_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_transfer_proto_goTypes = []any{
	(*TransferEntry)(nil),                          // 0: pb.TransferEntry
	(*TransferRecord)(nil),                         // 1: pb.TransferRecord
	(*CreateTransferRequest)(nil),                  // 2: pb.CreateTransferRequest
	(*CreateTransferResponse)(nil),                 // 3: pb.CreateTransferResponse
	(*CreateTransferResponse_AccountSnapshot)(nil), // 4: pb.CreateTransferResponse.AccountSnapshot
	(*timestamppb.Timestamp)(nil),                  // 5: google.protobuf.Timestamp
}
var file_rpc_transfer_proto_depIdxs = []int32{
	5, // 0: pb.TransferEntry.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: pb.TransferRecord.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: pb.CreateTransferResponse.transfer:type_name -> pb.TransferRecord
	0, // 3: pb.CreateTransferResponse.from_entry:type_name -> pb.TransferEntry
	0, // 4: pb.CreateTransferResponse.to_entry:type_name -> pb.TransferEntry
	4, // 5: pb.CreateTransferResponse.from_account:type_name -> pb.CreateTransferResponse.AccountSnapshot
	4, // 6: pb.CreateTransferResponse.to_account:type_name -> pb.CreateTransferResponse.AccountSnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_transfer_proto_init() }
func file_rpc_transfer_proto_init() {
	if File_rpc_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_transfer_proto_rawDesc), len(file_rpc_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transfer_proto_goTypes,
		DependencyIndexes: file_rpc_transfer_proto_depIdxs,
		MessageInfos:      file_rpc_transfer_proto_msgTypes,
	}.Build()
	File_rpc_transfer_proto = out.File
	file_rpc_transfer_proto_goTypes = nil
	file_rpc_transfer_proto_depIdxs = nil
}
