// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: service_go_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_go_bank_proto protoreflect.FileDescriptor

const file_service_go_bank_proto_rawDesc = "" +
	"\n" +
	"\x15service_go_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\n" +
	"user.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x0frpc_token.proto\x1a\x11rpc_account.proto\x1a\x12rpc_transfer.proto\x1a\x0frpc_entry.proto\x1a\x15rpc_update_user.proto\x1a\x16rpc_verify_email.proto2\xef%\n" +
	"\x06GoBank\x12\xba\x02\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\xfc\x01\x92A\xe4\x01\n" +
	"\x04Auth\x12\x13Register a new user\x1ahCreates a new user account. Username and email must be unique. Password is bcrypt-hashed before storage.*\n" +
	"CreateUserJ#\n" +
	"\x03200\x12\x1c\n" +
	"\x1aUser created successfully.J*\n" +
	"\x03403\x12#\n" +
	"!Username or email already exists.b\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\xb1\x02\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\xf6\x01\x92A\xd9\x01\n" +
	"\x04Auth\x12\x17Login and obtain tokens\x1aPAuthenticates credentials and returns a PASETO access token and a refresh token.*\tLoginUserJ#\n" +
	"\x03200\x12\x1c\n" +
	"\x1aAuthentication successful.J\x1a\n" +
	"\x03401\x12\x13\n" +
	"\x11Invalid password.J\x18\n" +
	"\x03404\x12\x11\n" +
	"\x0fUser not found.b\x00\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12\xba\x03\n" +
	"\x10RenewAccessToken\x12\x1b.pb.RenewAccessTokenRequest\x1a\x1c.pb.RenewAccessTokenResponse\"\xea\x02\x92A\xc6\x02\n" +
	"\x04Auth\x12\x12Renew access token\x1a\x97\x01Issues a new short-lived access token using a valid refresh token. Validated against the session store — blocked or mismatched sessions are rejected.*\x10RenewAccessTokenJ!\n" +
	"\x03200\x12\x1a\n" +
	"\x18New access token issued.J<\n" +
	"\x03401\x125\n" +
	"3Refresh token invalid, expired, or session blocked.J\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Session not found.b\x00\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/auth/renew_access\x12\xa0\x03\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"\xdf\x02\x92A\xc3\x02\n" +
	"\x04Auth\x12\x14Verify email address\x1a\x95\x01Verifies a user's email address using the id and secret_code from the verification link. The link expires after 15 minutes and can only be used once.*\vVerifyEmailJ%\n" +
	"\x03200\x12\x1e\n" +
	"\x1cEmail verified successfully.J.\n" +
	"\x03400\x12'\n" +
	"%Invalid or expired verification link.J'\n" +
	"\x03404\x12 \n" +
	"\x1eVerification record not found.b\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12\xcc\x04\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x8e\x04\x92A\xf6\x03\n" +
	"\x05Users\x12\x13Update current user\x1a\x91\x01Updates the authenticated user's profile. All fields are optional — only provided fields are updated. Password is bcrypt-hashed before storage.*\n" +
	"UpdateUserJ#\n" +
	"\x03200\x12\x1c\n" +
	"\x1aUser updated successfully.J:\n" +
	"\x03400\x123\n" +
	"1Invalid request parameters — validation failed.J)\n" +
	"\x03401\x12\"\n" +
	" Missing or invalid Bearer token.J,\n" +
	"\x03403\x12%\n" +
	"#Not authorized to update this user.J\x18\n" +
	"\x03404\x12\x11\n" +
	"\x0fUser not found.J1\n" +
	"\x03409\x12*\n" +
	"(Email already in use by another account.J\x1f\n" +
	"\x03500\x12\x18\n" +
	"\x16Internal server error.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x0e:\x01*2\t/v1/users\x12\xed\x02\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"\xa6\x02\x92A\x8b\x02\n" +
	"\bAccounts\x12\x11Create an account\x1aoCreates a new currency account for the authenticated user. Each user may hold at most one account per currency.*\rCreateAccountJ&\n" +
	"\x03200\x12\x1f\n" +
	"\x1dAccount created successfully.J2\n" +
	"\x03403\x12+\n" +
	")Account for this currency already exists.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12\xdf\x02\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"\xa1\x02\x92A\x84\x02\n" +
	"\bAccounts\x12\x0eGet an account\x1aTRetrieves a single account by ID. The account must belong to the authenticated user.*\n" +
	"GetAccountJ(\n" +
	"\x03200\x12!\n" +
	"\x1fAccount retrieved successfully.J-\n" +
	"\x03403\x12&\n" +
	"$Account belongs to a different user.J\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Account not found.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12\x86\x02\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\"\xc2\x01\x92A\xaa\x01\n" +
	"\bAccounts\x12\rList accounts\x1aIReturns a paginated list of all accounts owned by the authenticated user.*\fListAccountsJ$\n" +
	"\x03200\x12\x1d\n" +
	"\x1bPaginated list of accounts.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12\x84\x03\n" +
	"\vListEntries\x12\x16.pb.ListEntriesRequest\x1a\x17.pb.ListEntriesResponse\"\xc3\x02\x92A\xac\x02\n" +
	"\aEntries\x12\x15List activity entries\x1a\x7fReturns a paginated list of activity entries across all accounts owned by the authenticated user, ordered by most recent first.*\vListEntriesJ?\n" +
	"\x03200\x128\n" +
	"6Paginated list of authenticated user activity entries.J)\n" +
	"\x03401\x12\"\n" +
	" Missing or invalid Bearer token.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\r\x12\v/v1/entries\x12\x88\x03\n" +
	"\rUpdateAccount\x12\x18.pb.UpdateAccountRequest\x1a\x19.pb.UpdateAccountResponse\"\xc1\x02\x92A\xa1\x02\n" +
	"\bAccounts\x12\x16Update account balance\x1ahSets the balance of an account. The account must belong to the authenticated user. Balance must be >= 0.*\rUpdateAccountJ&\n" +
	"\x03200\x12\x1f\n" +
	"\x1dAccount updated successfully.J-\n" +
	"\x03403\x12&\n" +
	"$Account belongs to a different user.J\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Account not found.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/accounts/{id}\x12\xdd\x02\n" +
	"\rDeleteAccount\x12\x18.pb.DeleteAccountRequest\x1a\x19.pb.DeleteAccountResponse\"\x96\x02\x92A\xf9\x01\n" +
	"\bAccounts\x12\x11Delete an account\x1aRPermanently deletes an account. The account must belong to the authenticated user.*\rDeleteAccountJ\x19\n" +
	"\x03200\x12\x12\n" +
	"\x10Account deleted.J-\n" +
	"\x03403\x12&\n" +
	"$Account belongs to a different user.J\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Account not found.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x13*\x11/v1/accounts/{id}\x12\xf7\x04\n" +
	"\x0eCreateTransfer\x12\x19.pb.CreateTransferRequest\x1a\x1a.pb.CreateTransferResponse\"\xad\x04\x92A\x91\x04\n" +
	"\tTransfers\x12\x11Create a transfer\x1a\xc3\x01Atomically transfers funds between two accounts. The source account must belong to the authenticated user. Both accounts must hold the specified currency. Uses deadlock-safe transaction ordering.*\x0eCreateTransferJ]\n" +
	"\x03200\x12V\n" +
	"TTransfer completed. Returns transfer record, entries, and updated account snapshots.J3\n" +
	"\x03400\x12,\n" +
	"*Insufficient balance or currency mismatch.JB\n" +
	"\x03401\x12;\n" +
	"9Source account does not belong to the authenticated user.J1\n" +
	"\x03404\x12*\n" +
	"(Source or destination account not found.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/transfersB\xff\x06\x92A\xd3\x06\x12\x82\x03\n" +
	"\n" +
	"GoBank API\x12\xeb\x01A production-grade banking API built with Go, gRPC, and gRPC-Gateway.\n" +
	"\n" +
	"Supports user registration, authentication with access/refresh tokens (PASETO), multi-currency accounts, and atomic money transfers with deadlock-safe transactions.\"S\n" +
	"\x0eAhmed Alyapany\x12'https://github.com/a7medalyapany/GoBank\x1a\x18ahmedalyapany1@gmail.com**\n" +
	"\x03MIT\x12#https://opensource.org/licenses/MIT2\x051.0.0\x1a\x0elocalhost:8080\"\x01/*\x02\x01\x022\x10application/json:\x10application/jsonRB\n" +
	"\x03400\x12;\n" +
	"9Bad Request — invalid input or missing required fields.R:\n" +
	"\x03401\x123\n" +
	"1Unauthorized — missing or invalid Bearer token.RM\n" +
	"\x03403\x12F\n" +
	"DForbidden — authenticated but not allowed to access this resource.R=\n" +
	"\x03404\x126\n" +
	"4Not Found — the requested resource does not exist.R\x1f\n" +
	"\x03500\x12\x18\n" +
	"\x16Internal Server Error.ZP\n" +
	"N\n" +
	"\n" +
	"BearerAuth\x12@\b\x02\x12+Enter: **Bearer &lt;your_access_token&gt;**\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z&github.com/a7medalyapany/GoBank.git/pbb\x06proto3"

var file_service_go_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),         // 1: pb.LoginUserRequest
	(*RenewAccessTokenRequest)(nil),  // 2: pb.RenewAccessTokenRequest
	(*VerifyEmailRequest)(nil),       // 3: pb.VerifyEmailRequest
	(*UpdateUserRequest)(nil),        // 4: pb.UpdateUserRequest
	(*CreateAccountRequest)(nil),     // 5: pb.CreateAccountRequest
	(*GetAccountRequest)(nil),        // 6: pb.GetAccountRequest
	(*ListAccountsRequest)(nil),      // 7: pb.ListAccountsRequest
	(*ListEntriesRequest)(nil),       // 8: pb.ListEntriesRequest
	(*UpdateAccountRequest)(nil),     // 9: pb.UpdateAccountRequest
	(*DeleteAccountRequest)(nil),     // 10: pb.DeleteAccountRequest
	(*CreateTransferRequest)(nil),    // 11: pb.CreateTransferRequest
	(*CreateUserResponse)(nil),       // 12: pb.CreateUserResponse
	(*LoginUserResponse)(nil),        // 13: pb.LoginUserResponse
	(*RenewAccessTokenResponse)(nil), // 14: pb.RenewAccessTokenResponse
	(*VerifyEmailResponse)(nil),      // 15: pb.VerifyEmailResponse
	(*UpdateUserResponse)(nil),       // 16: pb.UpdateUserResponse
	(*CreateAccountResponse)(nil),    // 17: pb.CreateAccountResponse
	(*GetAccountResponse)(nil),       // 18: pb.GetAccountResponse
	(*ListAccountsResponse)(nil),     // 19: pb.ListAccountsResponse
	(*ListEntriesResponse)(nil),      // 20: pb.ListEntriesResponse
	(*UpdateAccountResponse)(nil),    // 21: pb.UpdateAccountResponse
	(*DeleteAccountResponse)(nil),    // 22: pb.DeleteAccountResponse
	(*CreateTransferResponse)(nil),   // 23: pb.CreateTransferResponse
}
var file_service_go_bank_proto_depIdxs = []int32{
	0,  // 0: pb.GoBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.GoBank.LoginUser:input_type -> pb.LoginUserRequest
	2,  // 2: pb.GoBank.RenewAccessToken:input_type -> pb.RenewAccessTokenRequest
	3,  // 3: pb.GoBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4,  // 4: pb.GoBank.UpdateUser:input_type -> pb.UpdateUserRequest
	5,  // 5: pb.GoBank.CreateAccount:input_type -> pb.CreateAccountRequest
	6,  // 6: pb.GoBank.GetAccount:input_type -> pb.GetAccountRequest
	7,  // 7: pb.GoBank.ListAccounts:input_type -> pb.ListAccountsRequest
	8,  // 8: pb.GoBank.ListEntries:input_type -> pb.ListEntriesRequest
	9,  // 9: pb.GoBank.UpdateAccount:input_type -> pb.UpdateAccountRequest
	10, // 10: pb.GoBank.DeleteAccount:input_type -> pb.DeleteAccountRequest
	11, // 11: pb.GoBank.CreateTransfer:input_type -> pb.CreateTransferRequest
	12, // 12: pb.GoBank.CreateUser:output_type -> pb.CreateUserResponse
	13, // 13: pb.GoBank.LoginUser:output_type -> pb.LoginUserResponse
	14, // 14: pb.GoBank.RenewAccessToken:output_type -> pb.RenewAccessTokenResponse
	15, // 15: pb.GoBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	16, // 16: pb.GoBank.UpdateUser:output_type -> pb.UpdateUserResponse
	17, // 17: pb.GoBank.CreateAccount:output_type -> pb.CreateAccountResponse
	18, // 18: pb.GoBank.GetAccount:output_type -> pb.GetAccountResponse
	19, // 19: pb.GoBank.ListAccounts:output_type -> pb.ListAccountsResponse
	20, // 20: pb.GoBank.ListEntries:output_type -> pb.ListEntriesResponse
	21, // 21: pb.GoBank.UpdateAccount:output_type -> pb.UpdateAccountResponse
	22, // 22: pb.GoBank.DeleteAccount:output_type -> pb.DeleteAccountResponse
	23, // 23: pb.GoBank.CreateTransfer:output_type -> pb.CreateTransferResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_go_bank_proto_init() }
func file_service_go_bank_proto_init() {
	if File_service_go_bank_proto != nil {
		return
	}
	file_user_proto_init()
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_token_proto_init()
	file_rpc_account_proto_init()
	file_rpc_transfer_proto_init()
	file_rpc_entry_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_verify_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_go_bank_proto_rawDesc), len(file_service_go_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_go_bank_proto_goTypes,
		DependencyIndexes: file_service_go_bank_proto_depIdxs,
	}.Build()
	File_service_go_bank_proto = out.File
	file_service_go_bank_proto_goTypes = nil
	file_service_go_bank_proto_depIdxs = nil
}
